# Generated by Django 3.0.7 on 2020-06-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20200611_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
