# Generated by Django 3.0.7 on 2020-06-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_remove_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
