# Generated by Django 3.0.7 on 2020-06-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_article_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='short_description',
        ),
    ]
