# Generated by Django 3.0.7 on 2020-06-13 18:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0009_auto_20200613_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, null=True),
        ),
    ]
