# Generated by Django 3.0.7 on 2020-06-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0010_auto_20200614_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img1',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
