# Generated by Django 3.0.7 on 2020-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0013_auto_20200630_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img1',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
