# Generated by Django 3.0.7 on 2020-06-30 14:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0015_auto_20200630_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
