
// authentications action types
export const AUTH_LOGIN_INIT = "AUTH_LOGIN_INIT";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

// user types

export const USER_PROFILE_VIEW_INIT = "USER_PROFILE_VIEW_INIT";
export const USER_PROFILE_VIEW_SUCCESS = "USER_PROFILE_VIEW_SUCCESS";
export const USER_PROFILE_VIEW_FAIL = "USER_PROFILE_VIEW_FAIL";

export const USER_PROFILE_EDIT_INIT = "USER_PROFILE_EDIT_INIT";
export const USER_PROFILE_EDIT_SUCCESS = "USER_PROFILE_EDIT_SUCCESS";
export const USER_PROFILE_EDIT_FAIL = "USER_PROFILE_EDIT_FAIL";

export const USER_ARTICLE_EDIT_INIT = "USER_ARTICLE_EDIT_INIT";
export const USER_ARTICLE_EDIT_SUCCESS = "USER_ARTICLE_EDIT_SUCCESS";
export const USER_ARTICLE_EDIT_FAIL = "USER_ARTICLE_EDIT_FAIL";

// article sent success or failure
export const SEND_NEW_ARTICLE_TO_SERVER_INIT = "SEND_NEW_ARTICLE_TO_SERVER_INIT";
export const SEND_NEW_ARTICLE_TO_SERVER_SUCCESS =
    "SEND_NEW_ARTICLE_TO_SERVER_SUCCESS";
export const SEND_NEW_ARTICLE_TO_SERVER_FAIL = "SEND_NEW_ARTICLE_TO_SERVER_FAIL";

// admin articles view
export const ADMIN_VIEW_ALL_ARTICLES_INIT = "ADMIN_VIEW_ALL_ARTICLES_INIT";
export const ADMIN_VIEW_ALL_ARTICLES_SUCCESS = "ADMIN_VIEW_ALL_ARTICLES_SUCCESS";
export const ADMIN_VIEW_ALL_ARTICLES_FAIL = "ADMIN_VIEW_ALL_ARTICLES_FAIL";

export const ADMIN_EDIT_ARTICLE_INIT = "ADMIN_EDIT_ARTICLE_INIT";
export const ADMIN_EDIT_ARTICLE_SUCCESS = "ADMIN_EDIT_ARTICLE_SUCCESS";
export const ADMIN_EDIT_ARTICLE_FAIL = "ADMIN_EDIT_ARTICLE_FAIL";

// user view and create
export const ADMIN_USER_LIST_VIEW_INIT = "ADMIN_USER_LIST_VIEW_INIT";
export const ADMIN_USER_LIST_VIEW_SUCCESS = "ADMIN_USER_LIST_VIEW_SUCCESS";
export const ADMIN_USER_LIST_VIEW_FAIL = "ADMIN_USER_LIST_VIEW_FAIL";

export const ADMIN_EDIT_USER_INIT = "ADMIN_EDIT_USER_INIT";
export const ADMIN_EDIT_USER_SUCCESS = "ADMIN_EDIT_USER_SUCCESS";
export const ADMIN_EDIT_USER_FAIL = "ADMIN_EDIT_USER_FAIL";

export const ADMIN_CREATE_USER_INIT = "ADMIN_CREATE_USER_INIT";
export const ADMIN_CREATE_USER_SUCCESS = "ADMIN_CREATE_USER_SUCCESS";
export const ADMIN_CREATE_USER_FAIL = "ADMIN_CREATE_USER_FAIL";


// personality test(questions)
export const QUESTIONS_PERSONALITY_TEST_INIT = "QUESTIONS_PERSONALITY_TEST_INIT";
export const QUESTIONS_PERSONALITY_TEST_SUCCESS = "QUESTIONS_PERSONALITY_TEST_SUCCESS";
export const QUESTIONS_PERSONALITY_TEST_FAIL = "QUESTIONS_PERSONALITY_TEST_FAIL";

// personality test(text)
export const TEXT_PERSONALITY_TEST_INIT = "TEXT_PERSONALITY_TEST_INIT";
export const TEXT_PERSONALITY_TEST_SUCCESS = "TEXT_PERSONALITY_TEST_SUCCESS";
export const TEXT_PERSONALITY_TEST_FAIL = "TEXT_PERSONALITY_TEST_FAIL";